add treasury overview documentation
PureStake/moonbeam-docs pull request #107
Opened 2021-06-23 22:33 UTC by eshaben

Add an overview page on the one treasury that Moonbase Alpha has, the community treasury. There was initially a plan for two treasuries, however it was decided that the parachain bond treasury is not necessary as it does not require the full capabilities of a treasury. So instead the parachain bond treasury was turned into account set in staking storage. 

So this overview goes over the community treasury!

2021-06-24 10:05 UTC, albertov19 commented
Looks gooooood!

Some comments:

 - Rememer to use variables from the `variables.yml` file. For example all the values in the table should be fetch from there, like `networks.moonbase.treasury.bond` and so on
 - I would make the tutorial Moonbeam generic, and just specify where certain things are Moonbase Alpha specific (this is something we might need to change in staking and governance as well). Now that we are approaching MainNet launch, we have to shift a little bit how we write documentation so it covers as many as all the networks as possible
 -

2021-06-24 10:11 UTC, albertov19 requested changes

2021-06-24 10:11 UTC, albertov19 commented on treasury/overview.md
> +|           Proposal bond          |     |                          5% of the proposed spend                                                       |
Use the `variables.yml` file

2021-06-24 10:11 UTC, albertov19 commented on treasury/overview.md
> +To fund the Treasury, 20% of each block's transactions fees will be sent to the Treasury. The remaining 80% of the fees are burned. The Treasury allows stakeholders to submit spending proposals to be
This first sentence sounds weird, probably "20% of each block's transactions fees will be allocated to it"? Or something similar

2021-06-24 10:11 UTC, albertov19 commented on treasury/overview.md
> +To deter spam, proposals must be submitted with a deposit, also known as a proposal bond. If the proposal bond is less than the proposal bond minimum, the proposal bond minimum must be submitted for
"If the proposal bond is less than the proposal bond minimum, the proposal bond minimum must be submitted for the deposit instead." -> "The proposal bond needs to be higher than a minimum amount, which can be changed by a governance proposal. So any token...."

2021-06-24 10:11 UTC, albertov19 commented on treasury/overview.md
> +To deter spam, proposals must be submitted with a deposit, also known as a proposal bond. If the proposal bond is less than the proposal bond minimum, the proposal bond minimum must be submitted for
"If the proposer's balance doesn't have enough funds to cover the deposit, the extrinsic will fail due to insufficient funds and you will have to pay transaction fees."

"If the proposer doesn't have enough funds to cover the deposit ...... funds, but transaction fees will still be deducted."

2021-06-24 18:38 UTC, eshaben commented
ok this is ready to be reviewed again... I tried to make this more moonbeam-generic, I know we spoke about having different tables for the different values, but I figure we can cross that bridge if/when we need to since the values are the same across each network right now... as long as "1 Token" is ok with you, if not I can change to a table per network

2021-06-28 17:03 UTC, eshaben commented
this is good to be reviewed again

2021-06-29 19:42 UTC, albertov19 approved these changes

2021-06-29 19:42 UTC, merged