Nifty wallet
PureStake/moonbeam-docs pull request #120
Opened 2021-07-16 19:07 UTC by eshaben

Create documentation around Nifty!
 
👉 Since all of the images are of a small screen, I had to use custom css to size the image so they wouldn't look too big on the docs page
👉 Nifty renders the token as ETH, there isn't a way to set it to MOVR. They do have a currency converter, but MOVR isn't on that list yet so left that as USD. Just included a note about it, but not sure if this is something we want to have fixed before publishing any docs as it could be pretty confusing 🤷‍♀️

2021-07-19 17:35 UTC, albertov19 requested changes
Looks good! I suggested some changes

2021-07-19 17:35 UTC, albertov19 commented on integrations/wallets/nifty.md
> +Please note that although your account balance shows ETH, it is not real ETH, and just DEV tokens.
I would add a !!! note here.

2021-07-19 19:35 UTC, eshaben commented
This is ready again!

2021-07-20 17:21 UTC, albertov19 requested changes
I've added some more comments, there are minor. I would also suggest that users can't connect Hardware wallets as it is not supported for Custom RPCs

2021-07-20 17:21 UTC, albertov19 commented on integrations/wallets/nifty.md
> +
I feel that not adding something here is kind of like an abrupt ending to this section. What happens after you click on "Create Account"?

2021-07-20 17:21 UTC, albertov19 commented on integrations/wallets/nifty.md
> +
Same comment as before, what happens when you click on "Import"?

2021-07-21 21:24 UTC, merged