Add Coinbase Wallet App Docs + additional
PureStake/moonbeam-docs pull request #234
Opened 2022-01-18 03:25 UTC by themacexpert

### Description
This PR includes the following:
- Adds documentation for Coinbase Wallet App
- Update democracy param based on spec in runtime
- Update Moonbeam Binary release version tag + sha256 hash for v0.18.1

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [x] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If images have been moved, I have created an additional PR in `moonbeam-docs-cn` to update images to their new paths
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2022-01-18 14:57 UTC, eshaben commented
@themacexpert Just a heads up... It looks like one of the names of the variables was changed from days to hours, so another PR will need to be opened in the moonbeam-docs-cn repo so it doesn't break the usage of it from the chinese site

2022-01-21 16:16 UTC, eshaben requested changes
I love these images!! 😍 

The index page icon is missing from `/tokens/connect/` aside from that there are a few little things but overall this is really great!!

2022-01-21 16:16 UTC, eshaben commented on tokens/connect/coinbase-wallet.md
> +You can download the Coinbase Wallet app from the iOS App Store or the Google Play Store. Coinbase maintains [this homepage](https://wallet.coinbase.com/?_branch_match_id=977295450874474909&_branch_r
I prefer to use more descriptive link text, I think what you could do here is something like

```You can [download the Coinbase Wallet app](https://wallet.coinbase.com/?_branch_match_id=977295450874474909&_branch_referrer=H4sIAAAAAAAAA8soKSkottLXT8%2FXS07SLddLzs%2FVD8%2FJynFKSy02zE4CAFZ0JzQfAAAA){target=_blank} from the iOS App Store or the Google Play Store.```

2022-01-21 19:47 UTC, themacexpert commented
Thanks for the review @eshaben! I cleaned up everything.

2022-01-25 17:36 UTC, themacexpert commented
Good catch thanks @eshaben! Fixed the logo and addressed the hidden comments.

2022-01-25 20:09 UTC, eshaben approved these changes
LGTM :sparkles:

2022-01-25 20:10 UTC, merged