Add documentation for Scaffold-ETH
PureStake/moonbeam-docs pull request #267
Opened 2022-02-25 09:49 UTC by hyd628

### Description

Adds a new page on how to set up Scaffold-ETH to use with Moonbeam networks. 

### Checklist

- [x] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [x] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [x] If images have been added, I have run the `compress-images.py` script to compress the images.
- [x] If images have been moved, I have created an additional PR in `moonbeam-docs-cn` to update images to their new paths
- [x] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [x] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2022-02-25 21:06 UTC, eshaben requested changes
I really love the layout of this guide! Nice job!! Just some minor things 🙂

2022-02-25 21:06 UTC, eshaben commented on builders/interact/scaffold-eth.md
> +1. The file we need to modify is `scaffold-eth/packages/hardhat/hardhat.config.js`. Under the `module.exports/networks` section, we want to add the network definitions for the Moonbeam network(s) tha
For all of the numbered list items throughout, no period is required at the end of the sentences

2022-02-25 21:06 UTC, eshaben commented on builders/interact/scaffold-eth.md
> +            accounts: ["Deployment Account Private Key"]
can you please use the variables for the url and chainIds here and throughout the guide?

2022-02-27 12:54 UTC, hyd628 commented
Thanks @eshaben . I have incorporated all the feedback.

2022-02-28 15:57 UTC, eshaben approved these changes
LGTM 🚀

2022-02-28 15:57 UTC, merged