update bridges section & chainbridge page
PureStake/moonbeam-docs pull request #298
Opened 2022-04-20 16:53 UTC by eshaben

### Description

This PR updates the Builders > Integrations > Bridges section and the ChainBridge page itself. It takes care of the following items:

- get rid of eth directory
- add intro diagram
- number & reorder images/diagrams
- general update to chainbridge docs

⭕️ I'll circle back to the checklist. Hoping to put a script together to move pages so that can be used to test & update the Chinese site with. ⭕️

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [x] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If images have been moved, I have created an additional PR in `moonbeam-docs-cn` to update images to their new paths
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables

### Corresponding PRs

https://github.com/PureStake/moonbeam-mkdocs/pull/78 -- ⭕️ Will need to circle back & update the CN mkdocs.yml file ⭕️

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2022-04-21 11:00 UTC, albertov19 requested changes
Thanks for fixing a bunch of styling issues this page had.  Left some minor feedback

2022-04-21 16:50 UTC, eshaben commented on builders/integrations/bridges/chainbridge.md
> - - [How the bridge works](/builders/integrations/bridges/eth/chainbridge/#how-the-bridge-works)
yeah that is why i removed it

2022-04-28 21:38 UTC, eshaben commented
@albertov19 I think it's difficult to put a solution in for ChainBridge that would apply for other bridging solutions since the bridge only goes between Moonbase Alpha and two other TestNets

I thought about a tabbed solution with a table in it, but it seems a bit much for this instance. Also not sure if it even makes sense to have a table in that scenario since `Chain A` would always be whatever network the tab is on 🤷‍♀️ 🤷‍♀️

2022-04-29 09:08 UTC, albertov19 commented
I think probably a tabbed table/list is the way to go. Even though it seems overkill for Chainbridge because it only connects Moonbase Alpha with Kovan/Rinkeby. For example, if another bridge connects Moonbase Alpha with other TestNets but also Moonbeam with 4 more networks you'll have 2 tabs with quite a bit of info in it. 

Not sure what is the best approach, but just an idea

2022-04-29 20:58 UTC, eshaben commented
right yeah I figured it would be fine for more robust bridges but was struggling with the "overkill" of it in this instance. also struggling to make it even look good because a list in the tab doesn't look good, and the one column table isn't much better but it works 😬

2022-05-02 12:26 UTC, albertov19 approved these changes
LGTM 🚀

2022-05-03 03:11 UTC, merged