Add Moonbase Alpha Sample DApps Tutorials
PureStake/moonbeam-docs pull request #306
Opened 2022-05-03 00:51 UTC by themacexpert

### Description
Adds brief tutorials for each of the Moonbase Alpha Sample DApps as well as a quick links section for DApp URLs and Github Repository URLs. Links to existing Moonbeam Docs site content are included where relevant. 

### Checklist

- [x] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [x] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If images have been moved, I have created an additional PR in `moonbeam-docs-cn` to update images to their new paths
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2022-05-03 05:06 UTC, eshaben requested changes
Looks good! Mostly just minor nitpicking... haha sorry!

Also not sure about the images being pieced together, I think that could cause some confusion. For WalletConnect, there is already an image that you could re-use: https://docs.moonbeam.network/images/builders/integrations/wallets/walletconnect/walletconnect-2.png

But not sure about the other images like `moonbase-4.png` and `moonbase-8.png`

2022-05-03 05:06 UTC, eshaben commented on builders/get-started/networks/moonbase.md
> +1. Connect your MetaMask Wallet and ensure you're on the Moonbase Alpha network
I think there are a few places where this line is copy pasta'd... wallet doesn't need to be capitalized here

2022-05-03 05:07 UTC, eshaben commented
Also not really related to this review, but just pointing it out here so I don't forget that the update to the `readme-banner` image is going to break the docs site when this gets merged. I need to fix it!

2022-05-06 06:29 UTC, themacexpert commented
Thanks for the review @eshaben, this should be good to go now 👍

2022-05-09 16:38 UTC, eshaben approved these changes
LGTM 🚀

2022-05-09 16:38 UTC, merged