Added Ankr as Endpoint Provider
PureStake/moonbeam-docs pull request #323
Opened 2022-05-17 08:45 UTC by kaymomin

- Added Ankr's RPC in the docs
- Added a compressed image

2022-05-17 10:42 UTC, albertov19 commented
Thanks @kaymomin  - Will Ankr support Moonriver and Moonbase Alpha?

2022-05-17 15:38 UTC, albertov19 commented
@kaymomin It would be preferable to add the public endpoint and endpoint info once you support all networks

2022-05-19 08:24 UTC, albertov19 commented
@kaymomin we prefer to wait until you have endpoints for all networks. Thanks for understanding

2022-06-21 12:17 UTC, kaymomin commented
@albertov19 just following up! There's a possibility that this might be longer as it relates more on those chains collaborating with Ankr directly.

My suggestion is either, we add what's already available or we close this PR, but I think it would be a disservice to developers to not be able to give them options.

Cheers!

2022-06-21 12:29 UTC, albertov19 commented
@kaymomin is it possible to at least offer an endpoint for Moonriver as well?

2022-06-21 14:09 UTC, albertov19 commented
@kaymomin could you merge master and also organize Ankr alphabetically in both the list and the actual section. Thanks

2022-06-21 15:28 UTC, albertov19 commented
@kaymomin you still need to fix conflicts 😉

2022-06-22 13:57 UTC, albertov19 commented
Also @kaymomin I noticed that you provide a public endpoint. You should add it (in alphabetical order) in: https://github.com/PureStake/moonbeam-docs/blob/master/.snippets/text/endpoints/moonbeam.md

If you also have a WSS endpoint (which would be very useful), please add it there.

2022-06-23 04:17 UTC, eshaben requested changes
Just a couple minor changes, and then as Alberto had suggested, you can also add the endpoint to this file: https://github.com/PureStake/moonbeam-docs/blob/master/.snippets/text/endpoints/moonbeam.md 🙂

2022-06-23 04:17 UTC, eshaben commented on builders/get-started/endpoints.md
> +To get started, head to the [Ankr Protocol](https://www.ankr.com/protocol/) page to make your first call!
```suggestion
To get started, head to the [Ankr Protocol](https://www.ankr.com/protocol/){target=_blank} page to make your first call!
```

2022-06-23 04:17 UTC, eshaben commented on builders/get-started/endpoints.md
> +2. Select the [Moonbeam Network](https://www.ankr.com/protocol/public/moonbeam/)
```suggestion
2. Select the [Moonbeam Network](https://www.ankr.com/protocol/public/moonbeam/){target=_blank}
```

2022-06-23 04:17 UTC, eshaben commented on builders/get-started/endpoints.md
> +[Ankr](https://www.ankr.com/){target=_blank} supports free, public RPC endpoints to 15 different blockchain ecosystems, with additional networks constantly being added. The Ankr Public RPC layer prov
```suggestion
[Ankr](https://www.ankr.com/){target=_blank} supports free, public RPC endpoints to 15 different blockchain ecosystems, with additional networks constantly being added. The Ankr public RPC layer provides fast and reliable access via API endpoints for anybody in the world to connect to a growing number of networks including Moonbeam. 
```

2022-06-24 11:19 UTC, albertov19 commented
@eshaben FYI - they added the other part in a separate PR -> https://github.com/PureStake/moonbeam-docs/pull/350

2022-06-24 18:54 UTC, eshaben approved these changes

2022-06-24 18:54 UTC, merged