Eshaben/update precompiles
PureStake/moonbeam-docs pull request #353
Opened 2022-07-09 02:40 UTC by eshaben

### Description

This PR addresses a few items:
-  general clean up for consistency throughout the docs
-  adds a new pallets section (combining pallets & precompiles didn't seem like the best idea, especially for example the staking pallet/precompile as that page would have been extremely long and there are some cases where there are pallets and no precompiles and vice versa)
- updates all of the precompile pages for consistency in format

Image paths need to be updated still, but I think it might be easier to do one clean sweep of updating the images after the translations are done

⭕️ Will complete the checklist after an initial review ⭕️

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [ ] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2022-07-21 13:43 UTC, albertov19 commented
@eshaben can you fix conflicts plz

2022-07-22 04:56 UTC, eshaben commented
@albertov19 fixed! ✅

2022-07-25 19:42 UTC, eshaben commented
@albertov19 this is ready to be reviewed. i didn't address the utility page being "half-done" because I don't know what else to add to it. I think it makes sense to keep it the way it is for consistency but definitely open to suggestions! 🙂

2022-07-26 09:48 UTC, albertov19 requested changes
Thanks for doing this and nitpicking (standardizing) lots of these pages. My main feedback is regarding the utility page, let me know what you think

2022-07-26 09:48 UTC, albertov19 commented on builders/pallets-precompiles/pallets/utility.md
> +Some of the functionality of the utility pallet is also available through a batch precompile. The precompile is a Solidity interface that enables you to perform batch calls using the Ethereum API. Pl
Remember what I mentioned that the batch precompile has nothing to do with the `utility` pallet

2022-07-26 09:48 UTC, albertov19 commented on builders/pallets-precompiles/pallets/utility.md
> +# The Utility Pallet
I wonder if we should add examples or something as this feels a bit empty. We could:

1. Explain a bit more derivative accounts (check the xcm-transactor page-> http://127.0.0.1:8000/builders/xcm/xcm-transactor/#general-xcm-definitions) We could then add a reference from the xcm-transactor page to here
2. Do an example with the batching?

2022-07-26 09:51 UTC, albertov19 commented
Ah also, check for warnings when building the page, I got a bunch of redirects not existing warnings

2022-07-26 16:43 UTC, eshaben commented
> Ah also, check for warnings when building the page, I got a bunch of redirects not existing warnings

Yes thank you, need to still create PR for mkdocs and chinese repo to reflect changes made here

2022-07-27 21:02 UTC, eshaben commented
@albertov19 this is ready again

2022-07-28 16:49 UTC, albertov19 approved these changes

2022-07-28 16:49 UTC, albertov19 commented
Looks good!!! 😎 🚀

2022-07-28 17:29 UTC, merged