update redirects for precompile pages
PureStake/moonbeam-docs pull request #372
Opened 2022-08-04 18:54 UTC by eshaben

### Description

This PR updates links to the old precompile pages to be new ones. The ahref report came back with [meta refresh redirect errors](https://help.ahrefs.com/en/articles/2433739-what-is-meta-refresh-redirect-and-why-is-it-considered-a-critical-issue) and our score is no longer 100 😢 

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [ ] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2022-08-04 19:08 UTC, themacexpert requested changes
Looks good, couple quick fixes

2022-08-04 19:08 UTC, themacexpert commented on builders/build/canonical-contracts.md
> +|   [ECRECOVER](/builders/pallets-precompiles/precompiles/eth-mainnet/#verify-signatures-with-ecrecover/){target=_blank}   | 0x0000000000000000000000000000000000000001 |
```suggestion
|   [ECRECOVER](/builders/pallets-precompiles/precompiles/eth-mainnet/#verify-signatures-with-ecrecover){target=_blank}   | 0x0000000000000000000000000000000000000001 |
```

2022-08-04 19:08 UTC, themacexpert commented on builders/build/canonical-contracts.md
> +|           [SHA256](/builders/pallets-precompiles/precompiles/eth-mainnet/#hashing-with-sha256/){target=_blank}           | 0x0000000000000000000000000000000000000002 |
```suggestion
|           [SHA256](/builders/pallets-precompiles/precompiles/eth-mainnet/#hashing-with-sha256){target=_blank}           | 0x0000000000000000000000000000000000000002 |
```

2022-08-04 19:08 UTC, themacexpert commented on builders/build/canonical-contracts.md
> +|       [RIPEMD160](/builders/pallets-precompiles/precompiles/eth-mainnet/#hashing-with-ripemd-160/){target=_blank}        | 0x0000000000000000000000000000000000000003 |
```suggestion
|       [RIPEMD160](/builders/pallets-precompiles/precompiles/eth-mainnet/#hashing-with-ripemd-160){target=_blank}        | 0x0000000000000000000000000000000000000003 |
```

2022-08-04 19:08 UTC, themacexpert commented on builders/build/canonical-contracts.md
> +|         [Identity](/builders/pallets-precompiles/precompiles/eth-mainnet/#the-identity-function/){target=_blank}         | 0x0000000000000000000000000000000000000004 |
```suggestion
|         [Identity](/builders/pallets-precompiles/precompiles/eth-mainnet/#the-identity-function){target=_blank}         | 0x0000000000000000000000000000000000000004 |
```

2022-08-04 19:08 UTC, themacexpert commented on builders/build/canonical-contracts.md
> +| [Modular Exponentiation](/builders/pallets-precompiles/precompiles/eth-mainnet/#modular-exponentiation/){target=_blank}  | 0x0000000000000000000000000000000000000005 |
```suggestion
| [Modular Exponentiation](/builders/pallets-precompiles/precompiles/eth-mainnet/#modular-exponentiation){target=_blank}  | 0x0000000000000000000000000000000000000005 |
```

2022-08-04 20:01 UTC, themacexpert approved these changes

2022-08-05 15:46 UTC, eshaben commented
Thanks @themacexpert !!

2022-08-05 15:56 UTC, merged