Adds Sidecar code snippet to Transfers API page
PureStake/moonbeam-docs pull request #386
Opened 2022-08-23 08:16 UTC by hyd628

### Description

Adds a code snippet example for retrieving and decoding Sidecar blocks for native token transfers to the Transfer API page, and links to the section from the Sidecar page. 

### Checklist

- [x] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [x] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [x] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [x] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [x] If images have been added, I have run the `compress-images.py` script to compress the images.
- [x] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2022-08-23 11:53 UTC, albertov19 requested changes
Looks good! I left some minor feedback. I think in general we need to clearly state that you can use the Sidecar API to monitor transfers from both the Substrate and Ethereum sides. Also, I would add a note that states that the code snippet is for demo purposes only? (Not sure if this is also available in the other snippets, if not, we should add it).

2022-08-23 11:53 UTC, albertov19 commented on builders/build/substrate-api/sidecar.md
> +## Sample Code for Monitoring Native Token Transfers { #sample-code-for-monitoring-native-token-transfers }
Would it make sense to say that this is including transfers using both the Substrate and Ethereum APIs?

2022-08-23 11:53 UTC, albertov19 commented on builders/get-started/eth-compare/transfers-api.md
> +Developers can also retrieve Moonbeam blocks and monitor transactions using [Substrate API Sidecar](https://github.com/paritytech/substrate-api-sidecar){target=_blank}, a REST API service for interac
Highlight that the transfers are using both Substrate and Ethereum. I prefer to be clear because the title says "Substrate API Sidecar"

2022-08-24 03:13 UTC, hyd628 commented
Thanks @albertov19 , I've incorporated the feedback.

2022-08-24 10:50 UTC, albertov19 approved these changes
Looks good on my end 🚀

2022-08-24 16:27 UTC, eshaben commented on builders/build/substrate-api/sidecar.md
> +The [Transfers API page](/builders/build/get-started/eth-compare/transfers-api/#using-substrate-api-sidecar){target=_blank} has a code snippet demonstrating how to use Substrate API Sidecar to retrie
```suggestion
The [Transfers API page](/builders/build/get-started/eth-compare/transfers-api/#using-substrate-api-sidecar){target=_blank} has a code snippet demonstrating how to use Substrate API Sidecar to retrieve and decode native token transfers sent with both Substrate and Ethereum API on Moonbeam networks. You can reference that as a starting point to build out backends that utilize Sidecar to listen to transfers on Moonbeam networks. 
```

2022-08-24 16:27 UTC, eshaben commented on builders/get-started/eth-compare/transfers-api.md
> +
```suggestion
```

2022-08-24 16:42 UTC, merged