Update Sidecar Docs with Latest Version
PureStake/moonbeam-docs pull request #471
Opened 2022-11-17 12:58 UTC by albertov19

### Description

Add changes to update Sidecar docs to the latest sidecar version

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [x] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [x] If images have been added, I have run the `compress-images.py` script to compress the images.
- [x] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables
- [x] If this page requires a disclaimer, I have added one

### Corresponding PRs

https://github.com/PureStake/moonbeam-docs-cn/pull/188

2022-11-17 17:56 UTC, eshaben requested changes

2022-11-17 17:56 UTC, eshaben commented on builders/get-started/eth-compare/tx-fees.md
> +    Transaction Fee = (Gas Price * Transaction Weight) / {{ networks.moonbase.tx_weight_to_gas_ratio }}
```suggestion
    Gas Price = Base Fee + Max Priority Fee Per Gas < Max Fee Per Gas ? 
                Base Fee + Max Priority Fee Per Gas : 
                Max Fee Per Gas;
    Transaction Fee = (Gas Price * Transaction Weight) / {{ networks.moonbase.tx_weight_to_gas_ratio }}
```

all of the other variables have a space between the words so I would change these just to be consistent

2022-11-17 17:56 UTC, eshaben commented on builders/get-started/eth-compare/tx-fees.md
> +The values of `Gas Price`, `MaxFeePerGas` and `MaxPriorityFeePerGas` for the applicable transaction types can be read from the block JSON object according to the structure described in [the Sidecar A
```suggestion
The values of `Gas Price`, `Max Fee Per Gas` and `Max Priority Fee Per Gas` for the applicable transaction types can be read from the block JSON object according to the structure described in [the Sidecar API page](/builders/build/substrate-api/sidecar/#evm-fields-mapping-in-block-json-object){target=_blank}, also truncated and reproduced below: 
```

2022-11-17 17:56 UTC, eshaben commented on builders/get-started/eth-compare/tx-fees.md
> +    | MaxPriorityFeePerGas | `extrinsics[extrinsic_number].args.transaction.eip1559.maxPriorityFeePerGas` |
```suggestion
    |     Max Fee Per Gas     |     `extrinsics[extrinsic_number].args.transaction.eip1559.maxFeePerGas`     |
    | Max Priority Fee Per Gas | `extrinsics[extrinsic_number].args.transaction.eip1559.maxPriorityFeePerGas` |
```

2022-11-17 17:56 UTC, eshaben commented on builders/get-started/eth-compare/tx-fees.md
> +The `BaseFee`, introduced in [EIP-1559](https://eips.ethereum.org/EIPS/eip-1559){target=_blank}, is a value set by the network itself. The `BaseFee` for `EIP1559` type transactions is currently stati
```suggestion
The `Base Fee`, introduced in [EIP-1559](https://eips.ethereum.org/EIPS/eip-1559){target=_blank}, is a value set by the network itself. The `Base Fee` for `EIP1559` type transactions is currently static on Moonbeam networks and has the following assigned value:
```

2022-11-17 17:56 UTC, eshaben commented on builders/get-started/eth-compare/tx-fees.md
> +    | BaseFee  | 100 Gwei |
```suggestion
    | Base Fee  | 100 Gwei |
```

2022-11-17 17:56 UTC, eshaben commented on builders/get-started/eth-compare/tx-fees.md
> +    | BaseFee  | 1 Gwei |
```suggestion
    | Base Fee  | 1 Gwei |
```

2022-11-17 17:56 UTC, eshaben commented on builders/get-started/eth-compare/tx-fees.md
> +    | BaseFee  | 1 Gwei |
```suggestion
    | Base Fee  | 1 Gwei |
```

2022-11-17 17:56 UTC, eshaben commented on variables.yml
> +      stable_version: 14.1.1
only MBA needs to be updated?

2022-11-18 10:13 UTC, albertov19 commented
@eshaben thanks for the review 😃 - I've applied the feedback (also in the CN repo)

2022-11-18 10:13 UTC, albertov19 commented on variables.yml
> +      stable_version: 14.1.1
Good catch!

2022-11-18 14:06 UTC, eshaben approved these changes
LGTM ✨

2022-11-18 14:06 UTC, eshaben commented on builders/get-started/eth-compare/tx-fees.md
> +    Gas Price = Base Fee + Max Priority Fee Per Gas< Max Fee Per Gas ?
```suggestion
    Gas Price = Base Fee + Max Priority Fee Per Gas < Max Fee Per Gas ? 
```

2022-11-18 14:10 UTC, merged