update preimage-related docs
PureStake/moonbeam-docs pull request #512
Opened 2023-01-17 04:16 UTC by eshaben

### Description

This PR updates the preimage-related docs for the RT2000 breaking changes. Reference: [Moonbeam PR description](https://github.com/PureStake/moonbeam/pull/1933) and [Substrate PR description](https://github.com/paritytech/substrate/pull/11649)

👉 Democracy Pallet Changes:
- note_preimage is moved to pallet-preimages
- note_preimage_imminent has been removed and there is no equivalent
- propose - now accepts a Bounded<Call> argument instead of a proposal hash. This can be defined by a proposal hash + length of the proposal, or the call to be executed per se
- Preimages storage item now lives in pallet-preimages

👉A new Preimage Pallet page has been added.

👉 Democracy Precompile Changes:
- The two functions that were not previously supported are now supported so I made appropriate changes there
- Added the associated Events
- Updated the preimage instructions as preimages need to be created now before a proposal can be submitted and it must be done from the new preimages page (Refer to [PR description](https://github.com/PureStake/moonbeam/pull/1933))

👉 How to Submit a Proposal Changes:
- Add all new images
- Submit preimages from the new preimages page

### Checklist

- [x] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [ ] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables
- [ ] If this page requires a disclaimer, I have added one

### Corresponding PRs

n/a

### After Translation Requirements

- [X] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

On the democracy precompile page:
-  `/images/builders/pallets-precompiles/precompiles/democracy/democracy-6.png` will need to be `democracy-7.png`
 - `/images/builders/pallets-precompiles/precompiles/democracy/democracy-7.png` will need to be `democracy-6.png`
 
All of the governance proposals images will need to be removed:
- `images/tokens/governance/proposals/proposals-*.png` all of these are to be removed

And they will need to be replaced with:
- `images/tokens/governance/proposals/new/proposals-*.png` and drop `new` from the path

2023-01-18 11:06 UTC, albertov19 requested changes
Looks good! Left some feedback :)

2023-01-18 11:06 UTC, albertov19 commented on builders/pallets-precompiles/precompiles/democracy.md
> +Now you can take the encoded proposal that you got from [Polkadot.js Apps](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmoonbeam-alpha.api.onfinality.io%2Fpublic-ws#/democracy){target=_blank} and su
In the near future, I would like us to move to examples with Polkadot.js SDK when it makes sense. I think this is an end user oriented tutorial more than anything else, so it maybe makes sense to keep it as such, but not sure what you think

2023-01-18 11:06 UTC, albertov19 commented on builders/pallets-precompiles/precompiles/democracy.md
> +Now you can take the encoded proposal that you got from [Polkadot.js Apps](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmoonbeam-alpha.api.onfinality.io%2Fpublic-ws#/democracy){target=_blank} and su
I feel in the section where you say:

```
First, you can get the preimage hash by navigating to the Governance tab of [Polkadot.js Apps](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmoonbeam-alpha.api.onfinality.io%2Fpublic-ws#/democracy) and selecting Preimages from the dropdown. From the Preimages page, click on + Add preimage, and take the following steps:
```

We are either missing an image taking you through the process, or you can put an Polkadot.js Apps URL direclty

2023-01-24 02:07 UTC, eshaben commented on builders/pallets-precompiles/pallets/preimage.md
> +- **requestPreimage**(bytes) - requests a preimage to be uploaded to the chain without paying any fees or deposits. If the preimage requests has already been provided on-chain by a user, their the re
```suggestion
- **requestPreimage**(bytes) - requests a preimage to be uploaded to the chain without paying any fees or deposits. If the preimage request has already been provided on-chain by a user, their related deposit is unreserved, and they no longer control the preimage. Emits a `Requested` event
```

2023-01-24 03:41 UTC, eshaben commented on builders/pallets-precompiles/precompiles/democracy.md
> +
Added a note to the preimage pallet page

2023-01-24 03:56 UTC, eshaben commented
Applied all of the feedback and switched around the images so that Xinxin only has to worry about removing images that are no longer needed once translations are done

Had a question about one of the democracy precompile methods, so asked J0 and waiting on an answer before I'll request a review again

2023-01-24 13:49 UTC, eshaben commented
Ok this is good to be reviewed again!

2023-01-24 17:29 UTC, albertov19 approved these changes
Great! Ship it 🚢

2023-01-24 19:17 UTC, merged