Revise Polkadot.js Apps Page to Include Talisman
PureStake/moonbeam-docs pull request #518
Opened 2023-01-19 06:56 UTC by themacexpert

### Description

This page revises the Connect to Moonbeam with Polkadot.js Apps page replacing info on importing accounts to Polkadot.js Apps to the browser (which is no longer supported) with info on creating and injecting accounts via Talisman.

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [x] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables
- [x] If this page requires a disclaimer, I have added one

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2023-01-24 05:08 UTC, eshaben requested changes
Awesomeee!! Looks good! Just a few comments 🙂

2023-01-24 05:08 UTC, eshaben commented on tokens/connect/talisman.md
> +As a Polkadot parachain, Moonbeam uses a [unified account structure](/learn/features/unified-accounts/) that allows you to interact with Substrate (Polkadot) functionality and Moonbeam's EVM, all fro
```suggestion
As a Polkadot parachain, Moonbeam uses a [unified account structure](/learn/features/unified-accounts/){target=_blank} that allows you to interact with Substrate (Polkadot) functionality and Moonbeam's EVM, all from a single Ethereum-style address. This unified account structure means that you don't need to maintain both a Substrate and an Ethereum account to interact with Moonbeam - instead, you can do it all with a single Ethereum private key.
```

2023-01-24 05:08 UTC, eshaben commented on tokens/connect/talisman.md
> +First, download and install the [Talisman extension](https://www.talisman.xyz/){target=_blank}. Once the extension opens up, you'll be prompted to either create a new wallet or import an existing one
```suggestion
First, download and install the [Talisman extension](https://www.talisman.xyz/){target=_blank}. Once the extension opens up, you'll be prompted to either create a new wallet or import an existing one. For the purposes of this demo, you'll create a new wallet. On the following screen you'll be prompted to create a password to secure the new wallet.  
```

avoid using we or let's, etc. (unless it's a page in the tutorials section 🙂)

2023-01-24 05:08 UTC, eshaben commented on tokens/connect/talisman.md
> +Talisman is a crypto-wallet that natively supports Substrate (Polkadot) and Ethereum accounts. The Talisman wallet browser extension is available on Google Chrome, Brave and Firefox, and a correspond
links to download each would be nice

2023-01-24 05:08 UTC, eshaben commented on tokens/connect/talisman.md
> +## Connecting Talisman to Polkadot.js Apps {: #connecting-talisman-to-polkadot.js-apps }
```suggestion
## Connecting Talisman to Polkadot.js Apps {: #connecting-talisman-to-polkadot.js-apps }

```

2023-01-24 05:08 UTC, eshaben commented on tokens/connect/talisman.md
> +![Connect Talisman Account to Polkadot.js Apps](/images/tokens/connect/talisman/talisman-7.png)
nice job with this image ❤️

2023-01-24 21:01 UTC, themacexpert commented on tokens/connect/polkadotjs.md
> +![Allow local in-browser account storage](/images/tokens/connect/polkadotjs/polkadotjs-9.png)
Done: https://github.com/PureStake/moonbeam-docs-cn/pull/213

2023-01-25 17:30 UTC, eshaben approved these changes
LGTM! 🚀

2023-01-25 17:36 UTC, merged