add local subsquid docs
PureStake/moonbeam-docs pull request #623
Opened 2023-04-19 05:27 UTC by eshaben

### Description

This PR adds a tutorial on indexing a local Moonbeam development node using Subsquid.

### Checklist

- [x] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [x] If images have been added, I have run the `compress-images.py` script to compress the images.
- [x] If this page requires a disclaimer, I have added one

### After Translation Requirements

- [x] No additional PRs are required after the translations are done

2023-04-24 17:00 UTC, albertov19 requested changes
Looks good! Left some feedback

2023-04-24 17:00 UTC, albertov19 commented on tutorials/integrations/local-subsquid.md
> +    sqd process
Was not working for  me. Initially I thought it was because I was not using `--sealing XXXX` but then it continued not working

2023-04-24 19:22 UTC, eshaben commented on tutorials/integrations/local-subsquid.md
> +      // ...
you can put it anywhere

2023-04-24 19:23 UTC, eshaben commented on tutorials/integrations/local-subsquid.md
> +      // ...
I'll delete the first `// ...` so users can feel free to add it to the top, but yeah doesn't really matter

2023-04-24 19:27 UTC, eshaben commented on tutorials/integrations/local-subsquid.md
> +// ...
I already shared the complete file, you just have to expand the "View the complete `processor.ts` file" note

2023-05-02 14:17 UTC, albertov19 approved these changes
LGTM

2023-05-02 14:53 UTC, merged