Update Remote EVM Execution XCM docs for XCM V3
PureStake/moonbeam-docs pull request #639
Opened 2023-04-27 16:01 UTC by eshaben

### Description

This PR updates the Remote Execution docs for XCM V3 and Weights V2. It also uses Polkadot.js API snippets instead of using the Polkadot.js Apps interface.

There are some images are no longer needed for this page, but keeping those in tact for CN version until translations are complete.

⚠️⚠️ Will circle back to the checklist after an initial review ⚠️⚠️

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [ ] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables
- [ ] If this page requires a disclaimer, I have added one

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2023-05-10 17:42 UTC, albertov19 requested changes
Looks good! Left a minor comment similar to other PRs.

2023-05-10 17:42 UTC, albertov19 commented on .snippets/code/remote-execution/send.js
> +const alice = keyring.addFromUri(PRIVATE_KEY);
Standardize this as mentioned before. Inputs variable at the top?

2023-05-11 09:24 UTC, albertov19 requested changes
Did you see my review on the XCM Transactor PR, maybe we can add a code snippet to handle account decoding? What do you think?

2023-05-11 09:24 UTC, albertov19 commented on builders/interoperability/xcm/remote-evm-calls.md
> +Where the `decodedAddress` corresponds to the address of the account who signed the transaction on the relay chain (in a 64 bytes format). When the XCM instruction gets executed in Moonbeam (Moonbase
```suggestion
Where the `decodedAddress` corresponds to the address of the account who signed the transaction on the relay chain (in a decoded 32 bytes format). When the XCM instruction gets executed in Moonbeam (Moonbase Alpha in this example), the origin will have mutated to the following multilocation:
```

2023-05-12 05:00 UTC, eshaben commented
> Did you see my review on the XCM Transactor PR, maybe we can add a code snippet to handle account decoding? What do you think?

Yeah the comment was on the Send & Execute PR and I made the changes there to include it in the example code snippet. This page doesn't have an existing example where I could implement it, so I added in a small snippet about it

2023-05-12 16:21 UTC, albertov19 approved these changes

2023-05-13 01:16 UTC, merged