Add API3 docs
PureStake/moonbeam-docs pull request #641
Opened 2023-04-29 00:25 UTC by eshaben

### Description

This PR updates the API3 docs initially submitted in https://github.com/PureStake/moonbeam-docs/pull/599

### Checklist

- [x] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jixa
- [x] If this page requires a disclaimer, I have added one

### After Translation Requirements

- [x] No additional PRs are required after the translations are done

2023-05-11 15:52 UTC, albertov19 requested changes
Some feedback

2023-05-11 15:52 UTC, albertov19 commented on builders/integrations/oracles/api3.md
> +![API3 Remix deploy](/images/builders/integrations/oracles/api3/api3-3.png)
Transparent bg

2023-05-11 15:52 UTC, albertov19 commented on builders/integrations/oracles/api3.md
> +![API3 Remix deploy](/images/builders/integrations/oracles/api3/api3-4.png)
Transparent bg

2023-05-12 04:26 UTC, eshaben commented on builders/integrations/oracles/api3.md
> +**Here is an example of a basic requester contract to request data from an Airnode:**
oh yeah missed that one. thanks!

2023-05-15 14:21 UTC, vanshwassan commented on builders/integrations/oracles/api3.md
> +![API3 Airnode](/images/builders/integrations/oracles/api3/api3-1.png)
Sure, here are all the images with a transparent bg:

![api3-1](https://github.com/PureStake/moonbeam-docs/assets/17065256/1ed36d4a-595e-4679-83af-696677b65576)
![api3-2](https://github.com/PureStake/moonbeam-docs/assets/17065256/b4f79f65-ed65-4030-b4f4-a6f4c072b3d0)
![api3-3](https://github.com/PureStake/moonbeam-docs/assets/17065256/b3689b3e-bc8a-4034-92e3-8d955c959ddf)
![api3-4](https://github.com/PureStake/moonbeam-docs/assets/17065256/738752df-2c66-412b-bbb4-ec1b0bb847be)
![api3-banner](https://github.com/PureStake/moonbeam-docs/assets/17065256/61230f52-bddb-4f53-adaf-934e189eb0e2)

2023-05-15 20:18 UTC, eshaben commented on builders/integrations/oracles/api3.md
> +![API3 Airnode](/images/builders/integrations/oracles/api3/api3-1.png)
@vanshwassan for some reason, the grey lines in the second image aren't coming in clear like they are in the other images. can it be easily fixed?

2023-05-16 23:07 UTC, vanshwassan commented on builders/integrations/oracles/api3.md
> +![API3 Airnode](/images/builders/integrations/oracles/api3/api3-1.png)
This should be better 👍🏻 
![api3-2](https://github.com/PureStake/moonbeam-docs/assets/17065256/363a78f2-79b8-4f31-a41b-7d16b4fc8ec2)

2023-05-17 01:51 UTC, eshaben commented on builders/integrations/oracles/api3.md
> +![API3 Airnode](/images/builders/integrations/oracles/api3/api3-1.png)
sweeet! thanks!

2023-05-17 14:14 UTC, merged