Chopsticks Update for v0.6.4
PureStake/moonbeam-docs pull request #668
Opened 2023-05-19 19:54 UTC by jboetticher

### Description

Chopsticks has had some recent updates, which means some of the commands don't work like they used to. `dry-run` still doesn't work with Moonbeam though.

I have also simplified & clarified sections of the docs.

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira

### After Translation Requirements

- [X] No additional PRs are required after the translations are done

2023-05-25 03:23 UTC, eshaben requested changes
everything worked as expected!

the bottom table has parameters wrapped in back ticks, but the rest of the tables in the guide do not. can you please add back ticks to anything that is a part of a command or code-related?

2023-05-25 03:23 UTC, eshaben commented on builders/build/substrate-api/chopsticks.md
> +The `npx @acala-network/chopsticks` command forks a chain, and includes following flags:
it feels like this should be in the prior section, but then i'm not so sure that the headers align

2023-05-25 03:23 UTC, eshaben commented on builders/build/substrate-api/chopsticks.md
>  When running a fork, by default it will be accessible at `ws://localhost:8000`. You will be able to interact with the parachain via libraries such as [Polkadot.js](https://github.com/polkadot-js/comm
break ws://localhost:8000 to a new line and wrap it in three backticks so its easy to copy

2023-05-25 03:23 UTC, eshaben commented on builders/build/substrate-api/chopsticks.md
> +    npx @acala-network/chopsticks --config=https://raw.githubusercontent.com/AcalaNetwork/chopsticks/master/configs/moonbase-alpha.yml
can you also break apart the rest of the commands in this file please?

2023-05-25 03:23 UTC, eshaben commented on builders/build/substrate-api/chopsticks.md
> +npx @acala-network/chopsticks xcm --r=kusama.yml --p=moonriver.yml --p=karura.yml
```suggestion
npx @acala-network/chopsticks xcm \
--r=kusama.yml \
--p=moonriver.yml \
--p=karura.yml
```

2023-05-25 03:23 UTC, eshaben commented on builders/build/substrate-api/chopsticks.md
>  To test out XCM messages between networks, you can fork multiple parachains and a relay chain locally. For example, the following will fork Moonriver, Karura, and Kusama given that you've downloaded
could probably add a bit more clarity here and say that you've downloaded the entire `configs` directory or at the very least the config for Moonriver, Karura, and Kusama.

2023-05-25 03:23 UTC, eshaben commented on builders/build/substrate-api/chopsticks.md
> +npx @acala-network/chopsticks xcm --r=kusama.yml --p=moonriver.yml --p=karura.yml
maybe add a note here stating that the chain name and raw github url can also be used

2023-05-25 03:23 UTC, eshaben commented on builders/build/substrate-api/chopsticks.md
> +- **`hashOrNumber` number | string** - if found, the chain head will be set to the block with the block number or block hash of this value
this seems like it should be above the actual json rpc request

2023-05-25 18:41 UTC, jboetticher commented on builders/build/substrate-api/chopsticks.md
> +|    Name   |        `npx @acala-network/chopsticks --config=moonbeam`                        |
This makes the width of the table larger than its container, causing the entire table to become a scrollview. Is that ok?

2023-05-25 19:55 UTC, eshaben requested changes
I played around with the table for the name, URL, and local path and ended up switching it to tabs and using a note as I think thats what looks best.

As for the Forking section it just seems redundant to the config section. So maybe just merge those two sections as a "Configure and Fork Moonbeam with Chopsticks" section or something

2023-05-25 20:50 UTC, jboetticher commented
I tried my best to combine them. Also included a left-over quickstart section... not sure if it fits or not

2023-06-01 19:47 UTC, eshaben commented on builders/build/substrate-api/chopsticks.md
> +The simplest way to fork Moonbeam is through the configuration files that are stored in the chopsticks GitHub repository:
```suggestion
The simplest way to fork Moonbeam is through the configuration files that are stored in the Chopsticks GitHub repository:  
```

2023-06-01 19:49 UTC, eshaben approved these changes
yeah I mean it does feel a little out of place, but i think it's fine in case someone just wants the command to get started without getting into the configuration details

2023-06-01 20:55 UTC, merged