add tenderly tutorial
PureStake/moonbeam-docs pull request #669
Opened 2023-05-24 01:47 UTC by themacexpert

### Description

Please explain the changes this PR addresses here.

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [ ] If pages have been moved around, I have run the `move-pages.py` script to move the pages and update the image paths on the chinese repo
    - [ ] After the script has been run, I have created an additional PR in `moonbeam-docs-cn`
- [x] If images have been added, I have run the `compress-images.py` script to compress the images.
- [ ] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables
- [ ] If this page requires a disclaimer, I have added one

### Corresponding PRs

Please link to any corresponding PRs here.

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [ ] No additional PRs are required after the translations are done

#### Items to be Updated

Please list any of the items that will need to be added or deleted after the translations are done here.

2023-05-25 04:28 UTC, eshaben requested changes
such a useful tool! my only concern with this tutorial is how some of it closely resembles the tenderly dev env page

i'll have to think about how we can maybe differentiate the two or possibly update the dev env page to remove some of the examples... not sure right now. lmk if you have any suggestions!

2023-05-25 04:28 UTC, eshaben commented on tutorials/eth-api/using-tenderly.md
> +2. Select the network the contract is deployed to. We'll select Moonbeam in this case
```suggestion
2. Select the network the contract is deployed to. We'll select **Moonbeam** in this case
```

2023-05-25 04:28 UTC, eshaben commented on tutorials/eth-api/using-tenderly.md
> +Let's craft a transaction to simulate against the Moonbeam network by taking the following steps:
this jumps over to simulations while the user is still on the contracts tab, so just add in that they have to switch to the Simulator tab

2023-05-25 04:28 UTC, eshaben commented on tutorials/eth-api/using-tenderly.md
> +Clearly, this simulated transaction is going to fail because we're trying to send 10,000 USDC that we don't have. But, with [Tenderly simulator](https://docs.tenderly.co/simulations-and-forks/how-to-
might want to add that the user will need to click Re-Simulate in the top right corner

2023-05-25 04:28 UTC, eshaben commented on tutorials/eth-api/using-tenderly.md
> +It's easy to create a fork with Tenderly. To do so, take the following steps:
users might still be on the simulator tab, so just a reminder to switch to forks would be nice

2023-05-25 04:28 UTC, eshaben commented on tutorials/eth-api/using-tenderly.md
> +Great! Now let's go ahead and try to perform the transfer from Baltathar now that Baltathar has plenty of USDC. To do so, take the following steps:
click Re-Simulate

2023-05-25 04:28 UTC, eshaben commented on tutorials/eth-api/using-tenderly.md
> +Great! Now let's go ahead and try to perform the transfer from Baltathar now that Baltathar has plenty of USDC. To do so, take the following steps:
oh actually they'll need to click New Simulation

2023-05-30 23:27 UTC, themacexpert commented
@eshaben I removed the bullet point section here and linked to the Tenderly page under the builders section to reduce the similarity between the two pages.

2023-06-01 20:29 UTC, eshaben approved these changes
nice job! looks good ✨

2023-06-01 20:58 UTC, merged