add v1 docs for the xcm sdk
PureStake/moonbeam-docs pull request #682
Opened 2023-06-23 14:45 UTC by eshaben

### Description

This PR adds new docs for the XCM SDK v1. Like with v0, it is split up by reference and usage. It aims to have better coverage on the reference page by including parameters and returned data.

### Checklist

- [ ] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [ ] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects

### After Translation Requirements

- [x] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site

2023-06-23 14:48 UTC, eshaben commented on builders/interoperability/xcm/xcm-sdk/v1/reference.md
> +    |      `min`       |    *number*    | The minimum amount of the asset that can be transferred |
@ekenigs this section in particular might need some help, haha  do you have better descriptions for some of these items?

2023-06-26 10:06 UTC, ekenigs requested changes

2023-06-26 10:06 UTC, ekenigs commented on builders/interoperability/xcm/xcm-sdk/v1/xcm-sdk.md
> +    amount == 0n
I think this condition is wrong.

2023-06-26 10:06 UTC, ekenigs commented on builders/interoperability/xcm/xcm-sdk/v1/xcm-sdk.md
> +    amount == 0n
Same.

2023-06-26 10:06 UTC, ekenigs commented on builders/interoperability/xcm/xcm-sdk/v1/xcm-sdk.md
> +  `You will pay ${data.source.fee.toDecimal()} ${
You forgot to use variables here instead of accessing it on `data`.

2023-06-26 17:20 UTC, eshaben commented on builders/interoperability/xcm/xcm-sdk/v1/reference.md
> +- `ChainAssetsData` - defines information needed to target the asset on the chain
Ok I've tried to make some sense of this and apply a generic statement here, but not sure if I did it effectively. Please review this in particular again and let me know if and how I can improve

2023-06-26 17:35 UTC, eshaben commented on builders/interoperability/xcm/xcm-sdk/v1/reference.md
> +### Transfer Data {: #transfer-data }
I've got some questions...

So, if the top level `min` amount is the minimum amount of the asset that can be transferred, and the `max` is the maximum amount of the asset that can be transferred then...

The source `max` differs from the top level `max` how?

The source `min` you said is the min amount to keep on the source chain? Due to existential deposit-like circumstance where an asset is not native? Does that apply here and that is why there is an existential deposit and min?

The destination min is the minimum amount that can be transferred? But how does that differ from the top level `min`?

2023-06-27 06:04 UTC, ekenigs commented on builders/interoperability/xcm/xcm-sdk/v1/reference.md
> +### Transfer Data {: #transfer-data }
> The source max differs from the top level max how?

Here you are right the `max` is the same. I copied it to the top level just so it's easier to access and users don't need to remember if it's in `source` or in `destination`.

> The destination min is the minimum amount that can be transferred? But how does that differ from the top level min?

Top lvl `min` is different than destination `min` and it's a bit more complex. Formula is:


```
// isTheSameAsset - is a condition where we check that asset what we send is the same with `min`, `existentialDeposit`, `fee`
min = (isTheSameAsset ? fee : 0) + (isTheSameAsset ? existentialDeposit : 0) + (isTheSameAsset ? min : 0)
```
The code itself looks like this.

```typescript
  const result = Big(0)
    .plus(balance.isSame(fee) ? fee.toBig() : Big(0))
    .plus(
      balance.isSame(existentialDeposit) &&
        balance.toBig().lt(existentialDeposit.toBig())
        ? existentialDeposit.toBig()
        : Big(0),
    )
    .plus(balance.toBig().lt(min.toBig()) ? min.toBig() : Big(0));
```

2023-06-27 07:06 UTC, ekenigs approved these changes
It looks good from my side. Good job as usual. 👍

2023-06-27 22:28 UTC, albertov19 approved these changes
LGTM!

2023-06-28 14:33 UTC, merged